services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle_21c_edu
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=123
      - APP_USER=hr
      - APP_USER_PASSWORD=hr
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./init-db:/container-entrypoint-initdb.d
    restart: always

volumes:
  oracle_data:
