CREATE SEQUENCE SQ_ESP NOCACHE;
CREATE SEQUENCE SQ_GAI NOCACHE;
CREATE SEQUENCE SQ_MUT NOCACHE;
CREATE SEQUENCE SQ_STT NOCACHE;
CREATE SEQUENCE SQ_PAS NOCACHE;

CREATE TRIGGER TG_SQ_ESP
BEFORE INSERT
ON ESPECIES
FOR EACH ROW
BEGIN
    :NEW.esp_id := SQ_ESP.NEXTVAL;
END;

CREATE TRIGGER TG_SQ_GAI
BEFORE INSERT
ON GAIOLAS
FOR EACH ROW
BEGIN
    :NEW.gai_id := SQ_GAI.NEXTVAL;
END;

CREATE TRIGGER TG_SQ_MUT
BEFORE INSERT
ON MUTACOES
FOR EACH ROW
BEGIN
    :NEW.mut_id := SQ_MUT.NEXTVAL;
END;

CREATE TRIGGER TG_SQ_STT
BEFORE INSERT
ON STATUS
FOR EACH ROW
BEGIN
    :NEW.stt_id := SQ_STT.NEXTVAL;
END;

CREATE TRIGGER TG_SQ_PAS
BEFORE INSERT
ON PASSAROS
FOR EACH ROW
BEGIN
    :NEW.pas_id := SQ_PAS.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TG_HESPECIES
BEFORE UPDATE OR DELETE ON ESPECIES
FOR EACH ROW
BEGIN
    INSERT INTO HESPECIES (
        ESP_ID,
        ESP_NOME,
        HESP_DT_INCLUSAO
    ) VALUES (
        :OLD.ESP_ID,
        :OLD.ESP_NOME,
        SYSDATE
    );
END;
/

CREATE OR REPLACE TRIGGER TG_HMUTACOES
BEFORE UPDATE OR DELETE ON MUTACOES
FOR EACH ROW
BEGIN
    INSERT INTO HMUTACOES (
        MUT_ID,
        MUT_DESCRICAO,
        HMUT_DT_INCLUSAO
    ) VALUES (
        :OLD.MUT_ID,
        :OLD.MUT_DESCRICAO,
        SYSDATE
    );
END;
/

CREATE OR REPLACE TRIGGER TG_HSTATUS
BEFORE UPDATE OR DELETE ON STATUS
FOR EACH ROW
BEGIN
    INSERT INTO HSTATUS (
        STT_ID,
        STT_SITUACAO,
        HSTT_DT_INCLUSAO
    ) VALUES (
        :OLD.STT_ID,
        :OLD.STT_SITUACAO,
        SYSDATE
    );
END;
/

CREATE OR REPLACE TRIGGER TG_HPASSAROS
BEFORE UPDATE OR DELETE ON PASSAROS
FOR EACH ROW
BEGIN
    INSERT INTO HPASSAROS (
        PAS_ID,
        PAS_ANILHA,
        PAS_DATA_NASC,
        PAS_SEXO,
        PAS_ESP_ID,
        PAS_MUT_ID,
        PAS_GAI_ID,
        PAS_STT_ID,
        PAS_NOT_FIS,
        HPAS_DT_INCLUSAO
    ) VALUES (
        :OLD.PAS_ID,
        :OLD.PAS_ANILHA,
        :OLD.PAS_DATA_NASC,
        :OLD.PAS_SEXO,
        :OLD.PAS_ESP_ID,
        :OLD.PAS_MUT_ID,
        :OLD.PAS_GAI_ID,
        :OLD.PAS_STT_ID,
        :OLD.PAS_NOT_FIS,
        SYSDATE
    );
END;
/

CREATE OR REPLACE TRIGGER TG_HGAIOLAS
BEFORE UPDATE OR DELETE ON GAIOLAS
FOR EACH ROW
BEGIN
    INSERT INTO HGAIOLAS (
        GAI_ID,
        GAI_NUMERO,
        HGAI_DT_INCLUSAO
    ) VALUES (
        :OLD.GAI_ID,
        :OLD.GAI_NUMERO,
        SYSDATE
    );
END;
/
